#!/usr/bin/env python3
"""
Generate docs/MAP.md from repository contents.
Called automatically by scripts/docs/validate_adr.py — do not edit MAP.md by hand.
"""

from __future__ import annotations

import re
from datetime import date
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS = REPO_ROOT / "docs"
ADR_DIR = DOCS / "adr"
FILENAME_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})-(\d{3})-([a-z0-9-]+)\.md$")
GENERATED_NOTE = (
    "<!-- auto-generated by scripts/docs/generate_docs_index.py; do not edit manually -->\n"
)


def parse_adr(path: Path) -> dict:
    text = path.read_text(encoding="utf-8-sig")
    parts = text.split("---", 2)
    meta = yaml.safe_load(parts[1]) if len(parts) >= 3 else {}
    return meta or {}


def status_label(meta: dict) -> str:
    status = meta.get("status", "unknown")
    note = meta.get("status_note")
    if note:
        return f"{status} ({note})"
    return str(status)


def adr_sort_key(item: tuple[Path, dict]) -> tuple[date, int]:
    path, meta = item
    d = meta.get("date")
    seq = meta.get("sequence")
    if isinstance(d, str) and isinstance(seq, int):
        try:
            return date.fromisoformat(d), seq
        except ValueError:
            pass
    match = FILENAME_RE.match(path.name)
    if match:
        try:
            return date.fromisoformat(match.group(1)), int(match.group(2))
        except ValueError:
            pass
    return date.min, 0


def adr_label(meta: dict, path: Path) -> str:
    d = meta.get("date")
    seq = meta.get("sequence")
    if isinstance(d, str) and isinstance(seq, int):
        return f"{d}-{seq:03d}"
    match = FILENAME_RE.match(path.name)
    if match:
        return f"{match.group(1)}-{match.group(2)}"
    return path.stem


def list_markdown(dir_path: Path, prefix: str) -> list[tuple[str, str]]:
    if not dir_path.is_dir():
        return []
    items: list[tuple[str, str]] = []
    for path in sorted(dir_path.glob("*.md")):
        if path.name == "README.md":
            continue
        rel = f"{prefix}/{path.name}"
        title = path.stem.replace("-", " ").title()
        first = path.read_text(encoding="utf-8-sig").splitlines()
        if first and first[0].startswith("# "):
            title = first[0][2:].strip()
        items.append((rel, title))
    return items


def generate_map(adrs: list[tuple[Path, dict]]) -> str:
    conventions = list_markdown(DOCS / "conventions", "conventions")
    workflow = list_markdown(DOCS / "workflow", "workflow")

    lines = [
        GENERATED_NOTE,
        "# Documentation map",
        "",
        "What lives where in this repository. "
        "**Updated automatically** when you run "
        "`python scripts/docs/validate_adr.py`.",
        "",
        "## Repository layout",
        "",
        "| Path | Contents |",
        "|------|----------|",
        "| `src/content/dags/` | Published DAG markdown (site) |",
        "| `src/content/nodes/` | MeSH-backed node vocabulary (site) |",
        "| `docs/adr/` | Architecture Decision Records |",
        "| `docs/conventions/` | Naming and schema rules |",
        "| `docs/workflow/` | Contribution and review guides |",
        "| [CONTRIBUTING.md](CONTRIBUTING.md) | How to submit a new DAG |",
        "| `_templates/dag-template.md` | DAG file template |",
        "| `_templates/adr-template.md` | ADR file template |",
        "| `scripts/dag/validate_dag.py` | DAG frontmatter validation |",
        "| `scripts/nodes/validate_nodes.py` | Node vocabulary validation |",
        "| `scripts/docs/validate_adr.py` | ADR validation + regenerates this file |",
        "| `scripts/docs/generate_docs_index.py` | MAP.md generator |",
        "| `scripts/deploy/` | Deployment checks (reserved) |",
        "",
        "## Decision log",
        "",
        "ADR index (newest first). Filename format: `YYYY-MM-DD-NNN-slug.md`. "
        "Schema: [adr/schema.json](adr/schema.json).",
        "",
        "| ID | Date | Title | Status | Tags |",
        "|----|------|-------|--------|------|",
    ]
    for path, meta in adrs:
        d = meta.get("date", "—")
        title = meta.get("title", path.stem)
        tags = ", ".join(meta.get("tags", [])) or "—"
        label = adr_label(meta, path)
        lines.append(
            f"| {label} | {d} | [{title}](adr/{path.name}) | "
            f"{status_label(meta)} | {tags} |"
        )

    lines.extend(["", "## Conventions (`docs/conventions/`)", ""])
    if conventions:
        lines.append("| File | Topic |")
        lines.append("|------|-------|")
        for rel, title in conventions:
            lines.append(f"| [{rel}]({rel}) | {title} |")
    else:
        lines.append("_No convention docs yet — see [conventions/README.md](conventions/README.md)._")

    lines.extend(["", "## Workflow (`docs/workflow/`)", ""])
    if workflow:
        lines.append("| File | Topic |")
        lines.append("|------|-------|")
        for rel, title in workflow:
            lines.append(f"| [{rel}]({rel}) | {title} |")
    else:
        lines.append("_See [workflow/README.md](workflow/README.md)._")

    lines.extend(
        [
            "",
            "## Other docs",
            "",
            "| File | Purpose |",
            "|------|---------|",
            "| [README.md](README.md) | Entry point for `docs/` |",
            "| [adr/README.md](adr/README.md) | How to write an ADR |",
            "| [adr/schema.json](adr/schema.json) | ADR frontmatter JSON Schema |",
            "| [../scripts/README.md](../scripts/README.md) | Script index |",
            "",
        ]
    )
    return "\n".join(lines)


def generate_docs_index() -> int:
    adr_paths = sorted(
        (p for p in ADR_DIR.glob("*.md") if FILENAME_RE.match(p.name)),
        key=lambda p: p.name,
        reverse=True,
    )
    adrs = [(p, parse_adr(p)) for p in adr_paths]
    adrs.sort(key=lambda item: adr_sort_key(item), reverse=True)

    (DOCS / "MAP.md").write_text(generate_map(adrs) + "\n", encoding="utf-8")
    return len(adrs)


def main() -> None:
    count = generate_docs_index()
    print(f"Wrote docs/MAP.md ({count} ADRs)")


if __name__ == "__main__":
    main()
