#!/usr/bin/env python3
"""
generate_wiki_sidebar.py
Scans the wiki directory and regenerates _Sidebar.md.
Pages are grouped into sections by filename prefix.
Run from the root of the cloned wiki repo.
"""

import os
from pathlib import Path

# Section definitions: (heading, filename prefixes or exact names)
SECTIONS = [
    ("Architecture Decisions", ["ADR-"]),
    ("Schema & Data Model",    ["DAG-Frontmatter", "Evidence-Level", "Tag-Taxonomy"]),
    ("Conventions",            ["File-Naming", "Node-and-Edge", "Category-"]),
    ("Contribution Workflow",  ["PR-and-Review", "Using-the-Validator", "Issue-to-DAG"]),
]

STANDALONE = ["Decision-Log"]
EXCLUDE    = {"Home", "_Sidebar", "_Footer"}


def page_title(stem: str) -> str:
    """ADR-003-Frontmatter-Schema → ADR-003: Frontmatter Schema"""
    if stem.startswith("ADR-") and len(stem) > 7:
        number = stem[4:7]          # "003"
        rest   = stem[8:].replace("-", " ")
        return f"ADR-{number}: {rest}"
    return stem.replace("-", " ")


def collect_pages(wiki_dir: Path) -> list[str]:
    return sorted(
        p.stem for p in wiki_dir.glob("*.md")
        if p.stem not in EXCLUDE
    )


def build_sidebar(pages: list[str]) -> str:
    lines = ["**[Home](Home)**", ""]
    assigned = set()

    for heading, prefixes in SECTIONS:
        matches = [p for p in pages if any(p.startswith(px) for px in prefixes)]
        if not matches:
            continue
        lines.append(f"**{heading}**")
        for p in matches:
            lines.append(f"- [{page_title(p)}]({p})")
            assigned.add(p)
        lines.append("")

    standalone_matches = [p for p in pages if p in STANDALONE]
    for p in standalone_matches:
        lines.append(f"**[{page_title(p)}]({p})**")
        assigned.add(p)

    # Anything that didn't match a section goes under Misc
    unmatched = [p for p in pages if p not in assigned]
    if unmatched:
        lines.append("")
        lines.append("**Other**")
        for p in unmatched:
            lines.append(f"- [{page_title(p)}]({p})")

    lines.append("")
    lines.append("<!-- auto-generated by scripts/generate_wiki_sidebar.py -->")
    lines.append("<!-- do not edit manually -->")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    wiki_dir = Path(".")
    pages = collect_pages(wiki_dir)
    sidebar = build_sidebar(pages)
    Path("_Sidebar.md").write_text(sidebar)
    print(f"_Sidebar.md updated with {len(pages)} pages.")
